
[tool.poetry]
name = "deeplocal"
version = "0.1.0"
description = ""
authors = ["sergiyslivka"]

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.3"
websockets = "^12.0"
requests = "^2.31"
waitress = "^2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
